#!/usr/bin/env bash
#a bash script that transfers a file from our client to a entered
num_entries=$#
root_key_path="/root/.ssh/id_rsa"
if [ $num_entries != 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	path_to_file=$1
	ip=$2
	username=$3
	path_to_key=$4

	if [ path_to_key == "${root_key_path}" ]; then
		sudo scp -i "$path_to_key" "$path_to_file" "$username@$ip:~/"
	else
		scp -i "$path_to_key" "$path_to_file" "$username@ip:~/"
	fi
fi

