#!/usr/bin/env bash
#a bash script that transfers a file from our client to a entered
num_entries=$#
if [ $num_entries != 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
else
	path_to_file=$1
	ip=$2
	username=$3
	path_to_key=$4
	scp -i "$path_to_key" "$path_to_file" "$username@$ip:~/"
fi

