#!/usr/bin/env bash
#
# This code tries to ping into the passed IP

count=0
if [ "$#" -eq 0 ]; then
	echo "5-is_the_host_on_the_network {IP_ADDRESS}"
else
	until [ $count -eq 5 ]
	do
		ping $1
		((count++))
	done

fi
