#!/usr/bin/env bash

# checking if any argument has been passed
count=0
if [ "$#" -eq 0 ]; then
	echo "5-is_the_host_on_the_network {IP_ADDRESS}"
else
	until [ $count -eq 5 ]
	do
		ping $1
		((count++))
	done

fi
